[package]
name = "errors"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "1.0.0-beta.10"
toml = "0.5"
image = "0.22"
syntect = { path = "/Users/uwe/repo/rust/syntect" }
